version: 0.0
os: linux
files:
  - source: /
    destination: /home/app
permissions:
  - object: /home/app
    pattern: "**"
    owner: root
    mode: 777
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
