spring:
  profiles:
    group:
      local: "localdb,common"
      server: "serverdb,common"
    active: local
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
      defer-datasource-initialization: true
    sql:
      init:
        encoding: UTF-8
        continue-on-error: true
        mode: always
---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: localdb
  datasource:
    url: jdbc:mariadb://localhost:3306/lof
    username: root
    password: 1234
---

spring:
  config:
    activate:
      on-profile: serverdb
  datasource:
    url: jdbc:mariadb://${lof.mariadb.url}:3306/lof
    username: root
    password: ${lof.mariadb.password}
