spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url : ENC(2kBwncqsGCr8VhEVdOvFbKTD+WkvjcZq/H/p2h/q4vxQPlG65/9Q00WxvCliMo+2sf2FdeOc6tsmA2coyCLCKki/byldpJKDx0IpLBpcNCmXhht5/TftM62OX6S1mB8S)
    password: ENC(9Mqc1gH7836zm/3OdCq7kD6lxVFqucFo)

  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      encoding: UTF-8
      continue-on-error: true
      mode: always
server:
  port: '80'

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
fcm:
  keyId: 'AAAA2e5oM2A:APA91bFkeAZM_08Vbliwn3C5_IR2jWF1GPgAS_9YYp071tRNyFossJP23OOTFMjwFq7HQW4HMU7K5XKee32u3cx8ioAlylFxK7SruyNO1iJy3sacuir-29GdosKdlKCBl6B_YfZj0xjd'