spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://database-1.c9zwet69f9b0.ap-northeast-2.rds.amazonaws.com:3306/lof
    # url : jdbc:mariadb://localhost:3306/lof
    password: soma17030
    # password : 1234
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      encoding: UTF-8
      continue-on-error: true
      mode: always
server:
  port: '80'