spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/lof
    password: '1234'
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      encoding: utf-8
      continue-on-error: true
server:
  port: '80'