spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      encoding: UTF-8
      continue-on-error: true
      mode: always

server:
  port: 80

---

spring:
  config:
    activate:
      on-profile: localdb
    import: localkey.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/lof
    username: root
    password: 1234
  sql:
    data: classpath:data.sql
    initialization-mode: always
slack:
  token: ${localkey.slack-api.token}

---

spring:
  config:
    activate:
      on-profile: serverdb
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${lof.mariadb.url}/lofDev
    username: root
    password: ${lof.mariadb.password}
  sql: #video 더미데이터
    data: classpath:data.sql
    initialization-mode: always
slack:
  token: ${lof.slack.token}

---

spring:
  config:
    activate:
      on-profile: mainserverdb
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${lof.mariadb.url}/lof
    username: root
    password: ${lof.mariadb.password}
slack:
  token: ${lof.slack.token}