ALTER table team convert to charset utf8;
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'DK','{"ko_KR" : "담원 기아", "en_US" : "DWG KIA"}','https://d654rq93y7j8z.cloudfront.net/teamImg/DWG KIA.png','[]');
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'NS','{"ko_KR" : "농심 레드포스", "en_US" : "Nongshim RedForce"}','https://d654rq93y7j8z.cloudfront.net/teamImg/NongShim REDFORCE.png','[]');
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'KT','{"ko_KR" : "kt 롤스터", "en_US" : "KT Rolster"}','https://d654rq93y7j8z.cloudfront.net/teamImg/kt Rolster.png','[]');
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'HLE','{"ko_KR" : "한화생명e스포츠", "en_US" : "Hanwha Life Esports"}','https://d654rq93y7j8z.cloudfront.net/teamImg/Hanwha Life Esports.png','[]');
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'DRX','{"ko_KR" : "DRX", "en_US" : "DRX"}','https://d654rq93y7j8z.cloudfront.net/teamImg/DRX.png','[]');
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'LSB','{"ko_KR" : "리브 샌드박스", "en_US" : "Liiv SANDBOX"}','https://d654rq93y7j8z.cloudfront.net/teamImg/Liiv SANDBOX.png','[]');
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'BRO','{"ko_KR" : "프레딧 브리온", "en_US" : "Fredit BRION"}','https://d654rq93y7j8z.cloudfront.net/teamImg/Fredit BRION.png','[]');
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'T1','{"ko_KR" : "T1", "en_US" : "T1"}','https://d654rq93y7j8z.cloudfront.net/teamImg/T1.png','[]');
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'GEN','{"ko_KR" : "젠지", "en_US" : "Gen.G"}','https://d654rq93y7j8z.cloudfront.net/teamImg/Gen.G.png','[]');
INSERT INTO team(id, name,name_list,img, match_list) VALUES (null,'KDF','{"ko_KR" : "광동 프릭스", "en_US" : "Kwangdong Freecs"}','https://d654rq93y7j8z.cloudfront.net/teamImg/KWANGDONG FREECS.png','[]');
